#!/usr/bin/env bash

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="${2:-}"

# only "normal" commits (`git commit` and `git commit -m "some message"`)
if [[ ! -z "$COMMIT_SOURCE" && "$COMMIT_SOURCE" != "message" ]]; then
    exit 0
fi

# capture the output of `goal commitmsg`
ACTIVE_GOAL=$(goal commitmsg 2>/dev/null)

# if the output is empty then let's dip
if [[ -z "$ACTIVE_GOAL" ]]; then
    exit 0
fi

if [[ "$COMMIT_SOURCE" == "message" ]]; then
    # message commits (with -m) have the message and only the message so just
    # append the goal details
    echo >> "$COMMIT_MSG_FILE"
    echo "$ACTIVE_GOAL" >> "$COMMIT_MSG_FILE"
else
    # want to keep the default commit message contents (which has a help
    # message) and put it at the end _after_ the goal details
    commit_msg=$(cat "$COMMIT_MSG_FILE")
    echo > "$COMMIT_MSG_FILE"
    echo "$ACTIVE_GOAL" >> "$COMMIT_MSG_FILE"
    echo "$commit_msg" >> "$COMMIT_MSG_FILE"
fi

exit 0
